url: "0.0.0.0" # the base hostname & protocol for your site

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
logo: /assets/images/logo-64.png
logo_dark: /assets/images/logo-bw-light.gif
title-nav: true
title: Hyperledger Grid

# COLLECTIONS
collections:
  portfolio:
    output: true

# BUILD SETTINGS
markdown: kramdown
sass:
  sass_dir: assets/_sass
  style: :compressed
keep_files: [./*]
source: ./source

# Enable site search
search: true
github: hyperledger/grid

description: "A project to provide a set of shared, reusable tools for building cross-industry supply chain solutions based on distributed ledger platforms"
header_text: >
   <h1>Hyperledger Grid</h1>
footer_text: >
  <p>
    <a href="http://www.linuxfoundation.org/privacy" target="_blank" title="Privacy Policy">Privacy Policy</a>
    •
    <a href="http://www.linuxfoundation.org/terms" target="_blank" title="Terms of Service">Terms of Service</a>
  </p>
  <p>
    <small class="copyright">Copyright © 2015-2019 contributors to Hyperledger Grid</small>
  </p>
permalink: /:categories/:year/:month/:day/:release/:title/
theme_settings:
  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  twitter: Hyperledger
  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
